{% set name = "river-ingester" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbotros/river/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 025e34ae3fadb51bed56e98f7457cf284273a4ce5a43e0d35f0ffc41ad553248

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("river-ingester", max_pin="x.x") }}
  # The ingester currently doesn't build on Windows, though admittedly not
  # much effort was put in to get this working. Redis runs on Linux/Mac
  # only anyways, so you'll need a Linux/Mac machine in the mix regardless.
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - boost-cpp
    - arrow-cpp
    - glog
    - river-cpp {{ version }}
  run:
    - gflags
    - boost-cpp
    - river-cpp {{ version }}
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/bin/river-ingester  # [osx]
    - test -f ${PREFIX}/bin/river-ingester  # [linux]

about:
  home: https://github.com/pbotros/river
  summary: High-throughput, structured, and persistent streaming
  description: |
    A high-throughput, structured streaming framework built atop Redis Streams, with optional support for persistence-to-disk. C++ and Python support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pbotros
