{% set name = "river-ingester" %}
{% set version = "1.0.11" %}

# appease linter
{% if libarrow is undefined %}
{% set libarrow = "15" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbotros/river/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04f6712d220a97fde76e3ed5998832c4a7ba790137cf656f8c2d1290077b8eaf
  patches:
    - patches/0001-disambiguate-make_unique-use-std-version-as-memory-a.patch

build:
  number: 6
  run_exports:
    - {{ pin_subpackage("river-ingester", max_pin="x.x") }}
  # The ingester currently doesn't build on Windows, though admittedly not
  # much effort was put in to get this working. Redis runs on Linux/Mac
  # only anyways, so you'll need a Linux/Mac machine in the mix regardless.
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - libboost-devel
    - libarrow
    - libparquet
    - spdlog
    - river-cpp {{ version }}
  run:
    - spdlog
    - river-cpp {{ version }}

test:
  commands:
    - test -f ${PREFIX}/bin/river-ingester  # [osx]
    - test -f ${PREFIX}/bin/river-ingester  # [linux]

about:
  home: https://github.com/pbotros/river
  summary: High-throughput, structured, and persistent streaming
  description: |
    A high-throughput, structured streaming framework built atop Redis Streams, with optional support for persistence-to-disk. C++ and Python support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pbotros
